gems:
 - jekyll-seo-tag
# Name of my personal web
name: Ilyas Habiburrahman
title: Ilyas Habiburrahman

# Name of author, my name (appear underneath each post and in the footer)
author: Ilyas Habiburrahman

# E-mail for personal contact
author_email: ilyashabiburrahman@gmail.com

# Short description of website
description: blog dedicated to store information about software development 

# Full url of the site
url: ilyashrn.github.io

# Twitter connection 
twitter:username: ilyashrn
